# Generated by Django 5.2.2 on 2025-06-13 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_habitacion_tipo_habitacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='id_habitacion',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('D', 'Disponible'), ('O', 'Ocupada'), ('M', 'Mantenimiento')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numero_habitacion',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.habitacion'),
        ),
    ]
