# Generated by Django 5.2.3 on 2025-06-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_rename_id_habitacion_habitacion_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='id',
            new_name='id_habitacion',
        ),
    ]
