# Generated by Django 5.2.2 on 2025-06-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_rename_id_habitacion_id_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
